import { Topbar } from "@/components/common/header/topbar";
import "../styles/index.scss";
import { Footer } from "@/components/common/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="minecraft-text">
        <Topbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
